#!/usr/bin/env python
"""%prog [options] DIRECTORY [DIRECTORY ...]

Re-create the ``Goct.fep`` or ``Ghyd.fep`` file using the appropriate 
equilibrium simulation file under <DIRECTORY>/FEP.

(This should only be necessary when the fep file was destroyed due to
a software error.)
"""

import os
import mdpow.equil
import mdpow.fep

import logging
logger = logging.getLogger('mdpow')


def fixFEP(solvent, fepfile, simfile, basedir):
    Gsolv = {'water': mdpow.fep.Ghyd,
             'octanol': mdpow.fep.Goct}
    S = mdpow.equil.Simulation(filename=simfile)
    # hack: need to explicitly add the Equilibrium/solvent dir to make it work
    # (note: I am not fixing the include path at the moment, see log...)
    simbasedir = os.path.join(basedir, 'Equilibrium', solvent)
    S.make_paths_relative(simbasedir)
    # TODO: fix includedir
    # S.dirs.includes[0] = '/sansom/gfio/oliver/Projects/pow/lib/python/POW/mdpow/top'
    G = Gsolv[solvent](simulation=S, basedir=basedir, permissive=True)

    # remove pre-0.2 standard-state correction (wrong!) and pdV (wrong)
    for crap in ('standardstate', 'pdV'):
        try:
            del G.results.DeltaA0[crap]
        except:
            pass
    G.save(fepfile)
    logger.info("Re-created %(fepfile)r for basedir=%(basedir)r", vars())
    return G

if __name__ == "__main__":
    import sys
    import os.path
    from optparse import OptionParser

    parser = OptionParser(usage=__doc__)
    parser.add_option('--solvent', dest="solvent",
                      help="rebuild fep for 'water', 'octanol', or 'all' [%default]",
                      metavar="NAME")
    parser.set_defaults(solvent="all")

    opts,args = parser.parse_args()
    
    gsolvnames = {'water':'Ghyd.fep', 'octanol':'Goct.fep'}
    if opts.solvent == "all":
        opts.solvent = gsolvnames.keys()
    else:
        if not opts.solvent in gsolvnames:
            raise ValueError("--solvent must be 'all' or one of %r" % gsolvnames.keys())
        opts.solvent = (opts.solvent,)

    for directory in args:
        if not os.path.exists(directory):
            logger.warn("Directory %r not found, skipping!", directory)
            continue
        logger.info("Rebuilding under directory %r... (can take a while)", directory)
        for solvent in opts.solvent:
            simfile = os.path.join(directory, solvent+'.simulation')
            fepfile = os.path.join(directory, 'FEP', solvent, gsolvnames[solvent])
            logger.info("[%(solvent)8s] equilibrim simulation: %(simfile)s", vars())
            logger.info("[%(solvent)8s] fep simulations:       %(fepfile)s", vars())
            
            try:
                G = fixFEP(solvent, fepfile, simfile, os.path.realpath(directory))
            except Exception,err:
                logger.warning(str(err))
