#!/usr/bin/env python
"""%prog [options] DIRECTORY

Run the free energy analysis for water and octanol in <DIRECTORY>/FEP
and return the octanol-water partition coefficient log P_ow.
"""

import os
import mdpow
import logging

logger = logging.getLogger('mdpow')

def load_gsolv(directory):
    FEPdir = os.path.join(directory, "FEP")
    
    files = {'water': os.path.join(FEPdir, 'water', 'Ghyd.fep'),
             'octanol': os.path.join(FEPdir, 'octanol', 'Goct.fep'),
             }
    files_not_found = dict(((solvent,fn) for solvent,fn in files.items()
                            if not os.path.exists(fn)))
    if len(files_not_found) > 0:
        raise OSError("Missing input files: %r" % files_not_found)
        
    logger.info("Reading water data %(water)r", files)
    gwat = mdpow.fep.Ghyd(filename=files['water'], basedir=directory)
    logger.info("Reading octanol data %(octanol)r", files)
    goct = mdpow.fep.Goct(filename=files['octanol'], basedir=directory)
    
    return gwat, goct


def run_pow(directory, **kwargs):
    gwat, goct = load_gsolv(directory)
    transferFE, pow = mdpow.fep.pOW(goct, gwat)
    if kwargs.get('plot', None):
        import matplotlib
        matplotlib.use('agg')  # quick non-interactive plotting
        from pylab import clf, title, savefig
        clf()
        gwat.plot(color='k', ls='--')
        goct.plot(color='r', ls='-')
        activate_subplot(1)
        title(r"[%s] $\Delta A^0 = %g$ kJ/mol" % (goct.molecule, transferFE))
        activate_subplot(2)
        title(r"$\log P_{OW} = %(pow)g$" % vars())
        savefig(kwargs['plot'])
        logger.info("Wrote graph to %(plot)r", kwargs)

def activate_subplot(numPlot):
    """Make subplot *numPlot* active on the canvas.

    Use this if a simple ``subplot(numRows, numCols, numPlot)``
    overwrites the subplot instead of activating it.
    """
    # see http://www.mail-archive.com/matplotlib-users@lists.sourceforge.net/msg07156.html
    from pylab import gcf, axes
    numPlot -= 1  # index is 0-based, plots are 1-based
    return axes(gcf().get_axes()[numPlot])

if __name__ == "__main__":
    import sys
    import os.path
    from optparse import OptionParser

    parser = OptionParser(usage=__doc__)
    parser.add_option('-p', '--plotfile', dest="plot",
                      help="plot dV/dlambda to FILE; use png or pdf suffix to "
                      "determine the file type. 'auto' generates a pdf file "
                      "DIRECTORY/dVdl.pdf and 'None' disables it [%default]", 
                      metavar="FILE")
    parser.set_defaults(plot="auto")
    opts,args = parser.parse_args()

    try:
        directory = args[0]
    except IndexError:
        logger.error("A directory is required. See --help.")
        sys.exit(1)

    if opts.plot == "auto":
        opts.plot = os.path.join(directory, "dVdl.pdf")
    elif opts.plot.lower() == "none":
        opts.plot = None

    run_pow(directory, plot=opts.plot)

    
